window.ANCIENT_TONGUE_LEXICON = [
  { ancient: "ar", meanings: ["agent marker", "actor"], status: "confirmed", register: "both" },
  { ancient: "en", meanings: ["object marker"], status: "confirmed", register: "both" },
  { ancient: "'s", meanings: ["direction", "intent toward", "toward"], status: "confirmed", register: "both" },
  { ancient: "eh", meanings: ["possession", "belonging"], status: "confirmed", register: "both" },
  { ancient: "i", meanings: ["plural denominator", "plural"], status: "confirmed", register: "both" },
  { ancient: "sul", meanings: ["to go", "go"], status: "confirmed", register: "ancient" },
  { ancient: "sal", meanings: ["to come", "come"], status: "confirmed", register: "ancient" },
  { ancient: "tsich", meanings: ["to take", "take"], status: "confirmed", register: "ancient" },
  { ancient: "tsach", meanings: ["to give", "give"], status: "confirmed", register: "ancient" },
  { ancient: "mel", meanings: ["to make", "make", "to create", "create"], status: "confirmed", register: "ancient" },
  { ancient: "mal", meanings: ["to break", "break"], status: "confirmed", register: "ancient" },
  { ancient: "nocht", meanings: ["to become", "become"], status: "confirmed", register: "ancient", pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "tsocht", meanings: ["to keep", "keep"], status: "confirmed", register: "ancient", pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "tsecht", meanings: ["to release", "release"], status: "confirmed", register: "ancient", pronunciation: "The final 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "la", meanings: ["to be", "be", "is", "are", "am"], status: "confirmed", register: "both" },
  { ancient: "licht", meanings: ["to remain", "remain"], status: "confirmed", register: "ancient", pronunciation: "The final 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "lin", meanings: ["to vanish", "vanish"], status: "confirmed", register: "ancient" },
  { ancient: "lan", meanings: ["to appear", "appear"], status: "confirmed", register: "ancient" },
  { ancient: "socht", meanings: ["to begin", "begin"], status: "confirmed", register: "ancient", pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "sacht", meanings: ["to continue", "continue", "big", "tall"], status: "confirmed", register: "both", notes: ["Polysemous root with both verbal and descriptive senses."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "tchich", meanings: ["to end", "end"], status: "confirmed", register: "ancient" },
  { ancient: "micht", meanings: ["bind", "attach"], status: "confirmed", register: "ancient", pronunciation: "The final 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "tcha", meanings: ["see"], status: "confirmed", register: "both" },
  { ancient: "kecht", meanings: ["hear"], status: "confirmed", register: "both", pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "nuhl", meanings: ["feel"], status: "confirmed", register: "both" },
  { ancient: "ru", meanings: ["to know", "know"], status: "confirmed", register: "both" },
  { ancient: "rutacht", meanings: ["remember"], components: ["ru", "tacht"], status: "confirmed", register: "ancient", notes: ["Concept stack: know + past."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "valru", meanings: ["forget", "not know"], components: ["val", "ru"], status: "confirmed", register: "both", notes: ["Carries both forgetfulness and negated knowledge."] },
  { ancient: "soo", meanings: ["sleep"], status: "confirmed", register: "both" },
  { ancient: "ji", meanings: ["in"], status: "confirmed", register: "both" },
  { ancient: "jo", meanings: ["out"], status: "confirmed", register: "both" },
  { ancient: "ja", meanings: ["here"], status: "confirmed", register: "both" },
  { ancient: "ja's", meanings: ["there"], status: "confirmed", register: "both" },
  { ancient: "rek", meanings: ["path"], status: "confirmed", register: "ancient" },
  { ancient: "rak", meanings: ["road"], status: "confirmed", register: "ancient" },
  { ancient: "raknacht", meanings: ["journey"], components: ["rak", "nacht"], lexicalized: true, canDecompose: true, status: "confirmed", register: "ancient", notes: ["Concept stack: road + future."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "to", meanings: ["step"], status: "confirmed", register: "ancient" },
  { ancient: "sulneh", meanings: ["crossing"], components: ["sul", "neh"], status: "confirmed", register: "ancient" },
  { ancient: "neh", meanings: ["beyond"], status: "confirmed", register: "ancient" },
  { ancient: "jija", meanings: ["inside"], status: "confirmed", register: "ancient" },
  { ancient: "jino", meanings: ["between"], status: "confirmed", register: "ancient" },
  { ancient: "ouk", meanings: ["above"], status: "confirmed", register: "ancient" },
  { ancient: "oun", meanings: ["below"], status: "confirmed", register: "ancient" },
  { ancient: "tacht", meanings: ["past"], status: "confirmed", register: "both", pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "nacht", meanings: ["future"], status: "confirmed", register: "both", pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "tem", meanings: ["present", "now"], status: "confirmed", register: "both" },
  { ancient: "sitacht", meanings: ["before"], components: ["si", "tacht"], status: "confirmed", register: "ancient", notes: ["Concept stack: small / prior + past."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "sinacht", meanings: ["after"], components: ["si", "nacht"], status: "confirmed", register: "ancient", notes: ["Concept stack: small / following + future."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "let", meanings: ["always"], status: "confirmed", register: "both" },
  { ancient: "lak", meanings: ["never"], status: "confirmed", register: "both" },
  { ancient: "locht", meanings: ["once"], status: "confirmed", register: "ancient", pronunciation: "The final 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "tsar", meanings: ["sun"], status: "confirmed", register: "both" },
  { ancient: "tsin", meanings: ["moon"], status: "confirmed", register: "both" },
  { ancient: "tsen", meanings: ["star"], status: "confirmed", register: "both" },
  { ancient: "ko", meanings: ["night"], status: "confirmed", register: "both" },
  { ancient: "ka", meanings: ["day"], status: "confirmed", register: "both" },
  { ancient: "hesh", meanings: ["fire"], status: "confirmed", register: "ancient" },
  { ancient: "hwir", meanings: ["water"], status: "confirmed", register: "both" },
  { ancient: "hoc", meanings: ["stone"], status: "confirmed", register: "ancient" },
  { ancient: "sec", meanings: ["sand"], status: "confirmed", register: "ancient" },
  { ancient: "sesh", meanings: ["wind"], status: "confirmed", register: "ancient" },
  { ancient: "tsal", meanings: ["sky"], status: "confirmed", register: "ancient" },
  { ancient: "kesh", meanings: ["flesh", "body"], status: "confirmed", register: "both" },
  { ancient: "keshir", meanings: ["blood"], components: ["kesh", "hwir"], status: "confirmed", register: "ancient", notes: ["Concept stack: flesh + water."] },
  { ancient: "keshoc", meanings: ["bone"], components: ["kesh", "hoc"], status: "confirmed", register: "ancient", notes: ["Concept stack: flesh + stone."] },
  { ancient: "kesheh", meanings: ["breath"], status: "confirmed", register: "ancient", notes: ["Meaning is confirmed, but internal derivation is still opaque."] },
  { ancient: "keshti", meanings: ["voice"], components: ["kesh", "ti"], status: "confirmed", register: "ancient", notes: ["Concept stack: flesh + sound."] },
  { ancient: "vacht", meanings: ["mind", "soul"], status: "confirmed", register: "both", pronunciation: "The final 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "nila", meanings: ["name"], status: "confirmed", register: "both" },
  { ancient: "valka", meanings: ["shadow"], status: "confirmed", register: "ancient", notes: ["Meaning is confirmed, but internal derivation is still opaque."] },
  { ancient: "soolie", meanings: ["dream"], status: "confirmed", register: "ancient", notes: ["Meaning is confirmed, but internal derivation is still opaque."] },
  { ancient: "lietacht", meanings: ["memory"], status: "confirmed", register: "ancient", notes: ["Meaning is confirmed, but internal derivation is still opaque."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "linvacht", meanings: ["spirit"], components: ["lin", "vacht"], lexicalized: true, canDecompose: true, status: "confirmed", register: "ancient", notes: ["Concept stack: vanish + soul."] },
  { ancient: "ruvalnacht", meanings: ["omen"], components: ["ru", "val", "nacht"], lexicalized: true, canDecompose: true, status: "confirmed", register: "ancient", notes: ["Can also be glossed as sign of the future or knowledge of the unknowable future."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "nachtnuh", meanings: ["fate"], components: ["nacht", "nuh"], status: "confirmed", register: "ancient", pronunciation: "The 'cht' retains the guttural fricative." },
  { ancient: "nuh", meanings: ["promise"], status: "confirmed", register: "both" },
  { ancient: "nu", meanings: ["oath"], status: "confirmed", register: "both" },
  { ancient: "soh", meanings: ["truth"], status: "confirmed", register: "both" },
  { ancient: "sicht", meanings: ["lie"], status: "confirmed", register: "both", pronunciation: "The final 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "valkecht", meanings: ["silence"], components: ["val", "kecht"], status: "confirmed", register: "ancient", notes: ["Concept stack: negation + hear."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "mah", meanings: ["mother"], status: "confirmed", register: "both" },
  { ancient: "tah", meanings: ["father"], status: "confirmed", register: "both" },
  { ancient: "kesh'skeh", meanings: ["kin"], components: ["kesh", "'s", "keh"], lexicalized: true, canDecompose: true, status: "confirmed", register: "ancient", notes: ["Directional marker participates in kinship compounding."] },
  { ancient: "kesh'skehsi", meanings: ["tribe"], components: ["kesh", "'s", "keh", "si"], lexicalized: true, canDecompose: true, status: "confirmed", register: "ancient" },
  { ancient: "valkesh", meanings: ["stranger"], components: ["val", "kesh"], lexicalized: true, canDecompose: true, status: "confirmed", register: "both" },
  { ancient: "cheechtkesh", meanings: ["enemy"], components: ["cheecht", "kesh"], status: "confirmed", register: "both", pronunciation: "The first 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "nuhkesh", meanings: ["guest"], components: ["nuh", "kesh"], lexicalized: true, canDecompose: true, status: "confirmed", register: "both" },
  { ancient: "yeket", meanings: ["children"], etymology: ["yecht", "kesh"], lexicalized: true, notes: ["Phonetic drift form."], status: "confirmed", register: "both" },
  { ancient: "ni", meanings: ["one"], status: "confirmed", register: "both" },
  { ancient: "no", meanings: ["two"], status: "confirmed", register: "both" },
  { ancient: "kei", meanings: ["many"], status: "confirmed", register: "both" },
  { ancient: "valkei", meanings: ["few"], components: ["val", "kei"], status: "confirmed", register: "both" },
  { ancient: "cheecht", meanings: ["evil", "negative"], status: "confirmed", register: "both", pronunciation: "The final 'cht' uses a guttural fricative like German 'Bach'." },
  { ancient: "loo", meanings: ["good", "positive"], status: "confirmed", register: "both" },
  { ancient: "si", meanings: ["short", "small"], status: "confirmed", register: "both" },
  { ancient: "teal", meanings: ["you"], status: "confirmed", register: "both" },
  { ancient: "neal", meanings: ["I", "self"], status: "confirmed", register: "both" },
  { ancient: "tsoum", meanings: ["existence"], status: "confirmed", register: "ancient" },
  { ancient: "val", meanings: ["negation"], status: "confirmed", register: "ancient" },
  { ancient: "rel", meanings: ["harm", "hurt"], status: "confirmed", register: "ancient" },
  { ancient: "koa", meanings: ["ruin"], status: "confirmed", register: "ancient" },
  { ancient: "tso", meanings: ["bring to", "bring upon", "brought upon"], status: "confirmed", register: "ancient" },
  { ancient: "tso'koa", meanings: ["bring ruin", "ruin", "ruination"], etymology: ["tso", "koa"], lexicalized: true, allowNominalReading: true, status: "confirmed", register: "ancient", notes: ["Lexicalized ritual form built from tso + koa."] },
  { ancient: "tsacht", meanings: ["peace", "death"], status: "confirmed", register: "ancient", notes: ["Intentional cultural ambiguity; preserve both senses."], pronunciation: "The final 'cht' uses a guttural fricative like German 'Nacht'." },
  { ancient: "nal", meanings: ["new"], status: "confirmed", register: "ancient" },
  { ancient: "kol", meanings: ["all"], status: "confirmed", register: "both" },
  { ancient: "tsol", meanings: ["land", "earth"], status: "confirmed", register: "ancient" }
];

window.ANCIENT_TONGUE_INFERRED_LEXICON = [
  { ancient: "ta", meanings: ["act", "to act", "perform action"], status: "inferred", register: "ancient", notes: ["Earlier assistant-proposed form; kept in experimental mode only."] },
  { ancient: "var", meanings: ["to move", "move"], status: "inferred", register: "ancient", notes: ["Earlier assistant-proposed motion root."] },
  { ancient: "vark", meanings: ["to rise", "rise"], status: "inferred", register: "ancient", notes: ["Earlier assistant-proposed motion root."] },
  { ancient: "vorn", meanings: ["to fall", "fall"], status: "inferred", register: "ancient", notes: ["Earlier assistant-proposed motion root."] },
  { ancient: "tor", meanings: ["to turn", "turn"], status: "inferred", register: "ancient", notes: ["Earlier assistant-proposed motion root."] },
  { ancient: "chi", meanings: ["open"], status: "inferred", register: "ancient", notes: ["Mentioned as non-canonical in the spec."] },
  { ancient: "chol", meanings: ["close"], status: "inferred", register: "ancient", notes: ["Earlier assistant-proposed antonym for open."] },
  { ancient: "vek", meanings: ["to strike", "strike"], status: "inferred", register: "ancient", notes: ["Earlier assistant-proposed action root."] },
  { ancient: "vekmal", meanings: ["to wound", "wound"], components: ["vek", "mal"], status: "inferred", register: "ancient", notes: ["Possible concept stack: strike + break."] },
  { ancient: "veklin", meanings: ["to kill", "kill"], components: ["vek", "lin"], status: "inferred", register: "ancient", notes: ["Possible concept stack: strike + vanish."] },
  { ancient: "veksoo", meanings: ["to sleep", "put to sleep"], components: ["vek", "soo"], status: "inferred", register: "ancient", notes: ["Experimental causative-style reading."] },
  { ancient: "rekh", meanings: ["storm"], status: "inferred", register: "ancient", notes: ["Earlier speculative environmental term."] },
  { ancient: "secvar", meanings: ["sandstorm"], components: ["sec", "var"], status: "inferred", register: "ancient", notes: ["Experimental concept stack: sand + move."] },
  { ancient: "tsarhesh", meanings: ["light"], components: ["tsar", "hesh"], status: "inferred", register: "ancient", notes: ["Experimental concept stack: sun + fire."] },
  { ancient: "rekmah", meanings: ["leader"], components: ["rek", "mah"], status: "inferred", register: "modern-fragment", notes: ["Earlier assistant-proposed social title."] },
  { ancient: "rekmahsi", meanings: ["chief"], components: ["rek", "mah", "si"], status: "inferred", register: "modern-fragment", notes: ["Experimental derived title."] },
  { ancient: "keshyeket", meanings: ["child"], components: ["kesh", "yeket"], status: "inferred", register: "ancient", notes: ["Experimental singularizing form based on confirmed 'yeket'."] },
  { ancient: "nuhlcheecht", meanings: ["fear"], components: ["nuhl", "cheecht"], status: "inferred", register: "modern-fragment", notes: ["Experimental concept stack: feel + negative."] },
  { ancient: "nuhlloo", meanings: ["love"], components: ["nuhl", "loo"], status: "inferred", register: "modern-fragment", notes: ["Experimental concept stack: feel + good."] },
  { ancient: "nuhlsec", meanings: ["grief"], components: ["nuhl", "sec"], status: "inferred", register: "modern-fragment", notes: ["Experimental emotional concept stack."] },
  { ancient: "nuhltar", meanings: ["hope"], status: "inferred", register: "modern-fragment", notes: ["Experimental emotional term from earlier brainstorming."] },
  { ancient: "ruval", meanings: ["uncertain knowledge", "intuition", "knowledge of the unknown"], components: ["ru", "val"], status: "inferred", register: "ancient", notes: ["Discussed in the spec as a plausible but non-canonical standalone form."] },
  { ancient: "yecht", meanings: ["that which originates from"], status: "inferred", register: "ancient", notes: ["Older root used for etymological support with yeket."] }
];
